config/routes.rb
Rails.application.routes.draw do
  #devise_for :users
  devise_for :users, controllers: { registrations: "registrations"}
  mount ActionCable.server => '/cable'
  root to: redirect(path: '/scans')

  get '/scans' => 'pages#scans'
  get 'notifications/new'

  # index ever used, ever?
  resources :groups, only: %i[create new]

  post 'groups/create_form' => 'groups#create_form'

  post 'groups/copy_form' => 'groups#copy_form'
  post 'groups/copy' => 'groups#copy'

  post 'groups/move_form' => 'groups#move_form'
  post 'groups/move' => 'groups#move'

  post 'groups/export_form' => 'groups#export_form'
  post 'groups/export' => 'groups#export'

  post 'groups/delete_form' => 'groups#delete_form'
  post 'groups/delete' => 'groups#delete'
  post 'groups/delete_clients_form' => 'groups#delete_clients_form'
  post 'groups/delete_clients' => 'groups#delete_clients'

  get 'pages/refresh' => 'pages#refresh', as: :group_refresh

  get '/pages/groups' => 'pages#groups'
  get '/pages/settings' => 'pages#settings', as: :global_settings
  post '/clients/global_search' => 'clients#global_search', as: :global_search

  get '/clients/search' => 'clients#search'
  post '/clients/search' => 'clients#search', as: :global_search_view
  #
  # order matters. keep this below other clients-routes, or it will always match.
  # alternatively, constraints need to be used (ie. regex for \d etc)
  get '/clients' => 'clients#index'
  get '/clients/:id' => 'clients#show'

  post 'setting/update_user_settings' => 'setting#update_user_settings', as: :update_user_settings
  post 'settings/update' => 'settings#update', as: :update_settings

  post 'scans/create' => 'scans#create'
  get 'scans/reload_status' => 'scans#reload_status'
  get 'scans/reload_finished' => 'scans#reload_finished'
  post 'scans/upload' => 'scans#upload'

  resources :clients

  # TODO: still used somewhere?
  post 'groups/scan_form' => 'groups#scan_form'
  post 'groups/scan' => 'groups#scan'


end

app/models/client.rb
class Client < ApplicationRecord
  has_many :ports, dependent: :destroy
  has_many :outputs, dependent: :destroy
  has_and_belongs_to_many :groups
  has_and_belongs_to_many :labels
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, presence: true
  has_and_belongs_to_many :clients, -> { distinct }
end

app/controllers/groups_controller.rb
# @restful_api 1.0
# Handle all things group related
class GroupsController < ApplicationController
  # @url /groups/new
  # @action GET
  #
  # renders :new, a form for group creation
  def new
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js { render :new }
    end
  end

  # @url /groups
  # @action POST
  #
  # Creates a new group
  #
  # @required [String] :group[:name] Name of the new group
  # @optional [Integer] :source_group ID of the source group
  # @optional [Array<Integer>] :selected_clients IDs of selected clients
  # @optional [String] :search true/false, indicator if :selected_clients are a result of a search
  # @optional [String] :move true/false, indicator if :selected_clients should be moved to the new group
  def create
    name = params[:group][:name]
    selected_clients = params[:selected_clients] if params[:selected_clients].present?
    search = ActiveModel::Type::Boolean.new.cast params[:search]
    source_group = search || params[:source_group].blank? ? nil : Group.find(params[:source_group])
    destination_group = Group.new
    destination_group.name = name.blank? ? 'Unknown' : name
    destination_group.icon = '<i class="fa ' + params[:group][:icon] + '"></i>'
    destination_group.mod = true

    render(:create_custom) && return unless destination_group.save # warn instead?

    respond_with_refresh('New empty group created') && return unless selected_clients.present?

    if params[:move].present? && params[:move].casecmp('true').zero?
      move_do(selected_clients, destination_group, source_group, search)
    else
      selected_clients.each { |selected| destination_group.clients << Client.find(selected) }
    end

    destination_group.save

    message = "New group '#{destination_group.name}' with #{selected_clients.length} clients saved."
    respond_with_refresh(message)
  end

  # @url /groups/create_form
  # @action POST
  #
  # Renders a form for group creation, providing clients
  def create_form
    prepare_form(:create_custom)
  end

  # @url /groups/move_form
  # @action POST
  #
  # Renders a form for moving clients
  def move_form
    prepare_form(:move)
  end

  # @url /groups/move
  # @action POST
  #
  # Moves clients to a group
  #
  # @required [String] :destination_group target group ID
  # @required [Integer] :source_group ID of the source group
  # @required [Array<Integer>] :selected_clients IDs of selected clients
  # @optional [String] :search true/false, indicator if :selected_clients are a result of a search
  def move
    destination_group = Group.find(params[:destination_group])
    source_group = Group.find(params[:source_group]) unless params[:source_group] == '-1'
    search = ActiveModel::Type::Boolean.new.cast params[:search]

    move_do(params[:selected_clients], destination_group, source_group, search)

    message = "Moved #{params[:selected_clients].length} clients to group '#{destination_group.name}'"
    respond_with_refresh(message)
  end

  # @url /groups/copy_form
  # @action POST
  #
  # Renders a form for moving clients
  def copy_form
    prepare_form(:copy)
  end

  # @url /groups/copy
  # @action POST
  #
  # Copies clients to a group
  #
  # @required [String] :destination_group target group ID
  # @required [Array<Integer>] :selected_clients IDs of selected clients
  def copy
    destination_group = Group.find(params[:destination_group])

    params[:selected_clients].each { |selected| destination_group.clients << Client.find(selected) }

    message = "Copied #{params[:selected_clients].length} clients to group '#{destination_group.name}'"
    respond_with_refresh(message)
  end

  # @url /groups/delete_clients_form
  # @action POST
  #
  # Renders a form for deleting clients
  def delete_clients_form
    prepare_form(:delete_clients)
  end

  # Renders a form for deleting clients
  def delete_form
    source_group ||= Group.find(params[:source_group]) unless params[:source_group].blank?
    clients = Client.find(params[:clients]) if params.key?(:clients)
    if (clients.blank? && source_group.clients.present?) || source_group.nil?
      respond_with_notify
    else
      clients ||= []
      locals = { source_group: source_group, clients: clients }
      respond_root_path_js(:delete_group, locals)
    end
  end

  # @url /groups/delete
  # @action POST
  #
  # Delete a group
  #
  # @required [String] :source_group ID of group to delete
  def delete
    source_group = Group.find(params[:source_group])

    source_group.clients.each { |client| client.destroy if client.groups.length == 1 }

    message = "Deleted Group '#{source_group.name}'"
    deleted = source_group.id
    source_group.destroy

    respond_to do |format|
      format.html {}
      format.js { render 'pages/group_refresh', locals: { message: message, close: true, delete: deleted, type: 'notice' } }
    end
  end

  # @url /groups/delete_clients
  # @action POST
  #
  # Deletes clients from a group (and the client itself if doesn't remain in any group or it was a search result)
  #
  # @required [String] :source_group ID of group to delete
  # @required [Array<Integer>] :selected_clients IDs of selected clients
  # @optional [String] :search true/false, indicator if :selected_clients are a result of a search
  def delete_clients
    search = ActiveModel::Type::Boolean.new.cast params[:search]
    source_group = Group.find(params[:source_group]) unless search
    selected_clients = params[:selected_clients]

    if search
      selected_clients.each do |selected|
        client = Client.find(selected)
        client.groups.each { |group| group.clients.delete(client) }
        client.destroy
      end
      message = "Deleted #{selected_clients.length} clients."
    else
      selected_clients.each do |selected|
        client = Client.find(selected)
        source_group.clients.delete(client)
        client.destroy if client.groups.empty?
      end
      message = "Deleted #{selected_clients.length} clients from group '#{source_group.name}'"
    end

    respond_with_refresh(message)
  end

  def scan_form
    clients = Client.find(params[:clients]) if params.key?(:clients)
    if clients.blank?
      respond_with_notify
    else
      locals = { clients: clients }
      respond_root_path_js(:scan, locals)
    end
  end

  # @url /groups/export_form
  # @action POST
  #
  # Renders a form to export clients
  def export_form
    clients = Client.find(params[:clients]) if params.key?(:clients)

    if clients.nil? || clients.empty?
      respond_with_notify
    else
      locals = { clients: clients }
      respond_root_path_js(:export, locals)
    end
  end

  # @url /groups/export
  # @action POST
  #
  # Exports selected clients' IPs as a .yml - file
  #
  # @required [String] :group[:file_name] desired file_name
  # @required [Array<Integer>] :selected_clients IDs of selected clients
  def export
    file_name = (params[:group][:file_name].present? ? params[:group][:file_name] : 'exported_clients')
    clients = Client.where(id: params[:selected_clients]) if params[:selected_clients].present?
    if file_name && clients.present?
      file_name << '.txt' unless file_name =~ /.+\.(yml|yaml|txt)$/
      if file_name =~ /.+\.(yml|yaml)$/
        exceptions = %w[id created_at updated_at icon client_id]
        data = clients.left_outer_joins(:outputs, :ports).distinct.map do |c|
          ary = [c.attributes.except(*exceptions)]
          ary  << { 'ports' => c.ports.map { |p| p.attributes.except(*exceptions) } }
          ary  << { 'outputs' => c.outputs.map { |o| o.attributes.except(*exceptions) } }
        end
        send_data YAML.dump(data), filename: file_name, type: 'application/yaml'
      else
        data = clients.map(&:ip).join("\n")
        send_data data, filename: file_name, type: 'text/plain'
      end
    else
      respond_with_notify('That didn\'t work.', 'alert')
    end
  end

  private

  def respond_with_refresh(message, type = 'notice')
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js { render 'pages/group_refresh', locals: { message: message, close: true, type: type } }
    end
  end

  def respond_with_notify(message = 'Please make a selection', type = 'alert')
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js { render 'pages/notify', locals: { message: message, type: type } }
    end
  end

  def respond_root_path_js(sym, locals)
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js { render sym, locals: locals }
    end
  end

  def prepare_form(sym)
    search = ActiveModel::Type::Boolean.new.cast params[:search]
    if search
      Struct.new('FakeGroup', :name, :id)
      source_group = Struct::FakeGroup.new('Custom search result', -1)
    end

    if params.key?(:clients)
      clients = Client.find(params[:clients])
      source_group ||= Group.find(params[:source_group]) unless params[:source_group].nil?
    end
    if clients.blank? || source_group.blank?
      respond_with_notify
    else
      locals = { source_group: source_group, clients: clients, search: search }
      respond_root_path_js(sym, locals)
    end
  end

  def move_do(selected_clients, destination_group, source_group, search)
    selected_clients.each do |selected|
      client = Client.find(selected)
      destination_group.clients << client
      next unless destination_group.save
      if search
        client.groups.each { |group| group.clients.delete client unless group == destination_group }
      else
        source_group.clients.delete client
      end
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_copy.html.erb
<style>
  .iconsholder {
    box-sizing: unset;
  }
  .howl-iconpicker-close {
    width: 260px;
  }
  .srchicons {
    text-align: center !important;
  }
  .howl-iconpicker {
    background: #fff;
  }
  .selectedicon {
    background: #1976D2!important;
    border-color: #1976D2!important;
    color: #fff;
  }
</style>
<%= simple_form_for :group, url: groups_copy_path, remote: true do |f| %>
  <div class="modal-content">
    <div class="modal-header" style="border-bottom: 1px solid rgba(0, 0, 0, 0.1); padding-bottom: 20px; margin-bottom: 50px;">
      <h5 class="center-align">Copy selected clients to </h5>
    </div>
    <div class="row">
      <div class="col s6">
        <div class="input-field">
          <input disabled value="<%= source_group.name %>" id="disabled" type="text" class="validate" autofocus>
          <label for="disabled">Source Group</label>
          <input type="hidden" name="source_group" value="<%= source_group.id %>">
        </div>
      </div>
      <div class="input-field col s6">
        <select id="destination_group" name="destination_group">
          <option disabled selected>Choose your option</option>
          <%= options_from_collection_for_select(Group.where.not(id: source_group.id).order(mod: :desc, name: :asc), :id, :name) %>
        </select>
        <label>Select target group</label>
      </div>
    </div>
    <div class="row center-align" >
      <div class="col s12" style="margin-bottom: 13px;">
        <label>Selected Clients</label>
      </div>
      <div class="col s12">
        <% clients.each do | temp_client | %>
            <div class="chip"><%= temp_client.ip %></div>
            <input type="hidden" name="selected_clients[]" value="<%= temp_client.id %>" />
        <% end %>
      </div>
    </div>
  </div>
  <div class="modal-footer">
    <%= f.button :submit, 'Copy', :class => 'modal-action disabled', :id => 'submit-copy' %>
    <a href="#" class="modal-action modal-close waves-effect waves-red btn-flat">Close</a>
  </div>
<% end %>

<script>
    $('#destination_group').on('change', function(){ $('#submit-copy').removeClass('disabled'); });
</script>

app/views/groups/_create_custom.html.erb
<style>
  .iconsholder {
    box-sizing: unset;
  }
  .howl-iconpicker-close {
    width: 260px;
  }
  .srchicons {
    text-align: center !important;
  }
  .howl-iconpicker {
    background: #fff;
  }
  .selectedicon {
    background: #1976D2!important;
    border-color: #1976D2!important;
    color: #fff;
  }
</style>
<%= simple_form_for :group, url: groups_path, remote: true do |f| %>
  <div class="modal-content">
    <div class="modal-header" style="border-bottom: 1px solid rgba(0, 0, 0, 0.1); padding-bottom: 20px; margin-bottom: 50px;">
      <h5 class="center-align">Create new group with selected clients</h5>
    </div>
    <div class="row">
      <div class="col s6">
        <div class="input-field">
          <input disabled value="<%= source_group.name %>" id="disabled" type="text" class="validate" autofocus>
          <label for="disabled">Source Group</label>
          <input type="hidden" name="source_group" value="<%= source_group.id %>">
          <input type="hidden" name="search" value="<%= search %>">
        </div>
        <label>Action applied to selected clients in new group</label>
        <div style="margin-bottom: 17px;"></div>
        <div class="switch">
          <label>Copy<input type="checkbox" name="move" value="true"><span class="lever"></span>Move</label>
        </div>
      </div>
      <div class="col s6">
        <%= f.input :name, :wrapper_html => { :class => "s12" } %>
        <%= f.input :icon, :input_html => {:class => "iconpicker"}, :wrapper_html => { :class => "s12" } %>
      </div>
    </div>
    <div class="row center-align">
      <div class="col s12" style="margin-bottom: 13px;">
        <label>Selected Clients</label>
      </div>
      <div class="col s12">
        <% clients.each do | temp_client | %>
            <div class="chip"><%= temp_client.ip %></div>
            <input type="hidden" name="selected_clients[]" value="<%= temp_client.id %>" />
        <% end %>
      </div>
    </div>
  </div>
  <div class="modal-footer">
    <%= f.button :submit, 'Create', :class => 'modal-action green darken-2' %>
    <a href="#" class="modal-action modal-close waves-effect waves-red btn-flat">Close</a>
  </div>
<% end %>
<script>
  $('.iconpicker').iconpicker(".iconpicker");
</script>

app/views/groups/_delete_clients.html.erb
<style>
  .iconsholder {
    box-sizing: unset;
  }
  .howl-iconpicker-close {
    width: 260px;
  }
  .srchicons {
    text-align: center !important;
  }
  .howl-iconpicker {
    background: #fff;
  }
  .selectedicon {
    background: #1976D2!important;
    border-color: #1976D2!important;
    color: #fff;
  }
</style>
<%= simple_form_for :group, url: groups_delete_clients_path, remote: true do |f| %>
  <div class="modal-content">
    <div class="modal-header" style="border-bottom: 1px solid rgba(0, 0, 0, 0.1); padding-bottom: 20px; margin-bottom: 50px;">
      <h5 class="center-align">Delete selected clients</h5>
      <input type="hidden" name="search" value="<%= search %>">
    </div>
    <div class="row">
      <div class="col s12">
        <div class="input-field">
          <input disabled value="<%= source_group.name %>" id="disabled" type="text" class="validate" autofocus>
          <label for="disabled">Source Group</label>
          <input type="hidden" name="source_group" value="<%= source_group.id %>">
        </div>
      </div>
    </div>
    <div class="row center-align">
      <div class="col s12" style="margin-bottom: 13px;">
        <label>Selected Clients</label>
      </div>
      <div class="col s12">
        <% clients.each do | temp_client | %>
            <div class="chip"><%= temp_client.ip %></div>
            <input type="hidden" name="selected_clients[]" value="<%= temp_client.id %>" />
        <% end %>
      </div>
    </div>
  </div>
  <div class="modal-footer">
    <%= f.button :submit, 'Delete', :class => 'modal-action red darken-4' %>
    <a href="#" class="modal-action modal-close waves-effect waves-red btn-flat">Close</a>
  </div>
<% end %>

app/views/groups/_delete_group.html.erb
<style>
  .iconsholder {
    box-sizing: unset;
  }
  .howl-iconpicker-close {
    width: 260px;
  }
  .srchicons {
    text-align: center !important;
  }
  .howl-iconpicker {
    background: #fff;
  }
  .selectedicon {
    background: #1976D2!important;
    border-color: #1976D2!important;
    color: #fff;
  }
</style>
<%= simple_form_for :group, url: groups_delete_path, remote: true do |f| %>
  <div class="modal-content">
    <div class="modal-header" style="border-bottom: 1px solid rgba(0, 0, 0, 0.1); padding-bottom: 20px; margin-bottom: 50px;">
      <h5 class="center-align">Delete whole group with selected clients</h5>
    </div>
    <div class="row">
      <div class="col s12">
        <div class="input-field">
          <input disabled value="<%= source_group.name %>" id="disabled" type="text" class="validate" autofocus>
          <label for="disabled">Source Group</label>
          <input type="hidden" name="source_group" value="<%= source_group.id %>">
        </div>
      </div>
    </div>
    <div class="row center-align">
      <div class="col s12" style="margin-bottom: 13px;">
        <label>Selected Clients</label>
      </div>
      <div class="col s12">
        <% clients.each do | temp_client | %>
            <div class="chip"><%= temp_client.ip %></div>
            <input type="hidden" name="selected_clients[]" value="<%= temp_client.id %>" />
        <% end %>
      </div>
    </div>
  </div>
  <div class="modal-footer">
    <%= f.button :submit, 'Delete', :class => 'modal-action red darken-4' %>
    <a href="#" class="modal-action modal-close waves-effect waves-red btn-flat">Close</a>
  </div>
<% end %>

app/views/groups/_export.html.erb
<style>
  .iconsholder {
    box-sizing: unset;
  }
  .howl-iconpicker-close {
    width: 260px;
  }
  .srchicons {
    text-align: center !important;
  }
  .howl-iconpicker {
    background: #fff;
  }
  .selectedicon {
    background: #1976D2!important;
    border-color: #1976D2!important;
    color: #fff;
  }
</style>
<%= simple_form_for :group, url: groups_export_path do |f| %>
  <div class="modal-content">
    <div class="modal-header" style="border-bottom: 1px solid rgba(0, 0, 0, 0.1); padding-bottom: 20px; margin-bottom: 50px;">
      <h5 class="center-align">Export selected clients to text file</h5>
    </div>
    <div class="row">
      <div class="col s12">
        <%= f.input :file_name, :wrapper_html => { :class => "s12" } %>
      </div>
      <div class="row center-align" >
        <div class="col s12" style="margin-bottom: 13px;">
          <label>Selected Clients</label>
        </div>
        <div class="col s12">
          <% clients.each do | temp_client | %>
              <div class="chip"><%= temp_client.ip %></div>
              <input type="hidden" name="selected_clients[]" value="<%= temp_client.id %>" />
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="modal-footer">
    <%= f.button :submit, 'Export', :class => 'modal-action', :onclick => "close_modal();" %>
    <a href="#" class="modal-action modal-close waves-effect waves-red btn-flat">Close</a>
  </div>
<% end %>

<script>
  function close_modal() {
      $(".modal").modal("close");
  }
</script>

app/views/groups/_group_content.html.erb
<% if Group.exists?(group_id) %>
  <% current_group = Group.find(group_id) %>
  <div class="card material-table">
    <div class="table-header table-header-groups">
      <span class="table-title truncate" style="margin-top: 15px; margin-bottom: 10px;"><%= "#{current_group.name}" %></span>
      <div>
        <div style="float: left;"><%= "#{current_group.icon}".html_safe %></div>
        <div style="float: right;" class="actions group-actions" id="<%= "#{current_group.id}" %>">
          <a href="#" data-position="bottom" data-delay="50" data-tooltip="Export selected clients" class="btn-flat nopadding tooltipped grp_export"><i class="material-icons">file_download</i></a>
          <a href="#" data-position="bottom" data-delay="50" data-tooltip="Select all visible clients in group" class="btn-flat nopadding tooltipped grp_mark_all"><i class="material-icons">check_box</i></a>
          <a href="#" data-position="bottom" data-delay="50" data-tooltip="Unselect all visible clients in group" class="btn-flat nopadding tooltipped grp_unmark_all"><i class="material-icons">check_box_outline_blank</i></a>
          <a href="#" data-position="bottom" data-delay="50" data-tooltip="Delete whole group" class="btn-flat nopadding tooltipped grp_delete"><i class="material-icons red-text text-darken-4">delete_forever</i></a>
          <a href="#" data-position="bottom" data-delay="50" data-tooltip="Delete selected clients" class="btn-flat nopadding tooltipped grp_delete_clients"><i class="material-icons red-text text-darken-4">delete</i></a>
          <a href="#" data-position="bottom" data-delay="50" data-tooltip="Move selected clients to another group" class="btn-flat nopadding tooltipped grp_move"><i class="material-icons blue-text text-darken-2">forward</i></a>
          <a href="#" data-position="bottom" data-delay="50" data-tooltip="Copy selected clients to another group" class="btn-flat nopadding tooltipped grp_copy"><i class="material-icons blue-text text-darken-2">content_copy</i></a>
          <a href="#" data-position="bottom" data-delay="50" data-tooltip="Add new group with selected clients" class="btn-flat nopadding tooltipped grp_new"><i class="material-icons green-text text-darken-2">group_add</i></a>
          <a href="#" data-position="bottom" data-delay="50" data-tooltip="Search in group" class="btn-flat nopadding tooltipped grp_search-toggle"><i class="material-icons yellow-text text-darken-4">search</i></a>
          <a href="#" data-position="bottom" data-delay="50" data-tooltip="Close group" class="btn-flat nopadding tooltipped grp_close"><i class="material-icons">close</i></a>
        </div>
      </div>
    </div>
    <table id="datatable-<%= "#{current_group.id}" %>" class="dt_init">
      <thead>
        <tr>
          <th>IP</th>
          <th>Hostname</th>
          <th>Operating System</th>
          <th>Ports</th>
        </tr>
      </thead>
      <tbody>
        <% current_group.clients.order(:ip).to_a.each do |current_client| %>
          <tr>
            <td><%= link_to "#{current_client.ip}", client_path(current_client.id), :remote => true, :id => current_client.id, :class => 'blue-text text-darken-2' %></td>
            <td><%= "#{current_client.hostname}" %></td>
            <td><%= "#{current_client.os}" %></td>
            <td><%= "#{current_client.ports.count}" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/groups/_move.html.erb
<style>
  .iconsholder {
    box-sizing: unset;
  }
  .howl-iconpicker-close {
    width: 260px;
  }
  .srchicons {
    text-align: center !important;
  }
  .howl-iconpicker {
    background: #fff;
  }
  .selectedicon {
    background: #1976D2!important;
    border-color: #1976D2!important;
    color: #fff;
  }
</style>
<%= simple_form_for :group, url: groups_move_path, remote: true do |f| %>
  <div class="modal-content">
    <div class="modal-header" style="border-bottom: 1px solid rgba(0, 0, 0, 0.1); padding-bottom: 20px; margin-bottom: 50px;">
      <h5 class="center-align">Move selected clients to </h5>
    </div>
    <div class="row">
      <div class="col s6">
        <div class="input-field">
          <input disabled value="<%= source_group.name %>" id="disabled" type="text" class="validate" autofocus>
          <label for="disabled">Source Group</label>
          <input type="hidden" name="source_group" value="<%= source_group.id %>">
          <input type="hidden" name="search" value="<%= search %>">
        </div>
      </div>
      <div class="input-field col s6">
        <select id="destination_group" name="destination_group">
          <option disabled selected>Choose your option</option>
          <%= options_from_collection_for_select(Group.where.not(id: source_group.id).order(mod: :desc, name: :asc), :id, :name) %>
        </select>
        <label>Select target group</label>
      </div>
    </div>
    <div class="row center-align" >
      <div class="col s12" style="margin-bottom: 13px;">
        <label>Selected Clients</label>
      </div>
      <div class="col s12">
        <% clients.each do | temp_client | %>
            <div class="chip"><%= temp_client.ip %></div>
            <input type="hidden" name="selected_clients[]" value="<%= temp_client.id %>" />
        <% end %>
      </div>
    </div>
  </div>

  <div class="modal-footer">
    <%= f.button :submit, 'Move', :class => 'modal-action' %>
    <a href="#" class="modal-action modal-close waves-effect waves-red btn-flat">Close</a>
  </div>
<% end %>

app/views/groups/copy.js.erb
$("#medium-modal").modal('open');
$("#medium-modal-content").html("<%= j(render('copy', :clients=> clients, :source_group=> source_group)) %>");
Materialize.updateTextFields();

app/views/groups/create_custom.js.erb
$("#medium-modal").modal('open');
$("#medium-modal-content").html("<%= j(render('create_custom', :clients=> clients, :source_group=> source_group, :search=> search)) %>");
Materialize.updateTextFields();

app/views/groups/export.js.erb
$("#medium-modal").modal('open');
$("#medium-modal-content").html("<%= j(render('export', :clients=> clients)) %>");
Materialize.updateTextFields();

app/views/groups/group_content.js.erb
<% group_ids.each do |group_id| %>
    // update the group content
    $("#group_content_<%= group_id %>").html("<%= j(render('groups/group_content', :group_id => group_id, :message => message)) %>");
<% end %>

app/views/groups/move.js.erb
$("#medium-modal").modal('open');
$("#medium-modal-content").html("<%= j(render('move', :clients=> clients, :source_group=> source_group, :search=> search)) %>");
Materialize.updateTextFields();

app/views/groups/scan.js.erb
$("#modal-content").html("<%= j(render('scan', :clients=> clients)) %>");
Materialize.updateTextFields();

app/views/groups/select_error.js.erb
<%= render(:template => 'main/notify', :handlers => [:erb], :formats => [:js], locals:{message: message}) %>