config/routes.rb
Rails.application.routes.draw do
  #devise_for :users
  devise_for :users, controllers: { registrations: "registrations"}
  mount ActionCable.server => '/cable'
  root to: redirect(path: '/scans')

  get '/scans' => 'pages#scans'
  get 'notifications/new'

  # index ever used, ever?
  resources :groups, only: %i[create new]

  post 'groups/create_form' => 'groups#create_form'

  post 'groups/copy_form' => 'groups#copy_form'
  post 'groups/copy' => 'groups#copy'

  post 'groups/move_form' => 'groups#move_form'
  post 'groups/move' => 'groups#move'

  post 'groups/export_form' => 'groups#export_form'
  post 'groups/export' => 'groups#export'

  post 'groups/delete_form' => 'groups#delete_form'
  post 'groups/delete' => 'groups#delete'
  post 'groups/delete_clients_form' => 'groups#delete_clients_form'
  post 'groups/delete_clients' => 'groups#delete_clients'

  get 'pages/refresh' => 'pages#refresh', as: :group_refresh

  get '/pages/groups' => 'pages#groups'
  get '/pages/settings' => 'pages#settings', as: :global_settings
  post '/clients/global_search' => 'clients#global_search', as: :global_search

  get '/clients/search' => 'clients#search'
  post '/clients/search' => 'clients#search', as: :global_search_view
  #
  # order matters. keep this below other clients-routes, or it will always match.
  # alternatively, constraints need to be used (ie. regex for \d etc)
  get '/clients' => 'clients#index'
  get '/clients/:id' => 'clients#show'

  post 'setting/update_user_settings' => 'setting#update_user_settings', as: :update_user_settings
  post 'settings/update' => 'settings#update', as: :update_settings

  post 'scans/create' => 'scans#create'
  get 'scans/reload_status' => 'scans#reload_status'
  get 'scans/reload_finished' => 'scans#reload_finished'
  post 'scans/upload' => 'scans#upload'

  resources :clients

  # TODO: still used somewhere?
  post 'groups/scan_form' => 'groups#scan_form'
  post 'groups/scan' => 'groups#scan'


end

app/models/client.rb
class Client < ApplicationRecord
  has_many :ports, dependent: :destroy
  has_many :outputs, dependent: :destroy
  has_and_belongs_to_many :groups
  has_and_belongs_to_many :labels
end

app/controllers/clients_controller.rb
# @restful_api 1.0
# Client display and search
class ClientsController < ApplicationController
  def index
    require_relative '../nmap/envizon_cpe'
  end

  # @url /clients/:id
  # @action GET
  #
  # renders client details
  def show
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js { render :show, locals: { client: Client.find(params[:id]) } }
    end
  end

  # @url /clients/global_search
  # @action POST
  #
  # @required [Hash<_unused, Hash>] :search_name Name of the resulting search group
  # @optional [String] :group[:name] Name of the new group
  def global_search
    @clients = Client.all

    if params.key?(:search)
      @search_name = (params[:search_name].empty? ? 'Custom Search' : params[:search_name])

      or_result = nil
      params[:search].each_pair do |_not_used, param|
        next unless %i[table name value not].all? { |key| param[key].present? }

        matched = match_search_element(@clients, param)

        if param.key?(:or) && param[:or].casecmp('true').zero?
          or_result = match_or_search(or_result, matched)
        elsif or_result
          or_result = match_or_search(or_result, matched)
          @clients = match_and_search(@clients, or_result)
          or_result = nil
        else
          @clients = match_and_search(@clients, matched)
        end
      end

      if or_result
        @clients = match_and_search(@clients, or_result)
        or_result = nil
      end

      respond_to do |format|
        format.html { redirect_back fallback_location: root_path }
        format.js { render :search_result }
      end
    else
      respond_to do |format|
        format.html { redirect_back fallback_location: root_path }
        format.js { render :select_error }
      end
    end
  end

  def search; end

  def match_search_element(clients, input)
    table = input[:table].downcase
    name = input[:name].downcase
    value = input[:value].downcase

    unless %w[output_port output_client].include?(table)
      table_record = table.classify.constantize
      arel_table = table_record.arel_table
    end

    result = if table == 'client'
               clients.where(arel_table[name].matches("%#{value}%"))
             elsif table == 'port' && name == 'number'
               if value =~ /\A\d+\Z/
                 clients.joins(table.pluralize.to_sym)
                        .where(arel_table[name]
                        .eq(value))
               else
                 match_and_search(clients, clients.joins(:ports))
               end
             elsif table == 'output'
               output(clients, input)
             elsif %w[output_port output_client].include?(table)
               output_helper(clients, input)
             elsif table_record.column_names.include?(name)
               clients.joins(table.pluralize.to_sym)
                      .where(arel_table[name]
                      .matches("%#{value}%"))
             end
    is_not = value.present? ? input[:not].casecmp('true').zero? : !input[:not].casecmp('true').zero?

    result = clients.where.not(id: result.pluck(:id)).group(:id) if is_not && result
    result
  end

  private

  def output(clients, input)
    value = input[:value].downcase if input[:value].present?
    output_param_name = { name: 'name', value: value, not: 'false' }

    output_param_value = { name: 'value', value: value, not: 'false' }

    if value.present?
      output_param_name[:table] = 'output_client'
      output_param_value[:table] = 'output_client'
      result_output_client = match_or_search(match_search_element(clients, output_param_name),
                                             match_search_element(clients, output_param_value))

      output_param_name[:table] = 'output_port'
      output_param_value[:table] = 'output_port'
      result_output_port = match_or_search(match_search_element(clients, output_param_name),
                                           match_search_element(clients, output_param_value))
      match_or_search(result_output_client, result_output_port)
    else
      match_or_search(match_and_search(clients, clients.joins(:outputs)),
                      match_and_search(clients, clients.joins(ports: :outputs)))
    end
  end

  def output_helper(clients, input)
    table_name = input[:table].downcase
    name = input[:name].downcase
    value = input[:value].downcase

    arel_table = Output.arel_table

    if table_name.include?('client')
      clients.joins(:outputs)
             .where(arel_table[name]
             .matches("%#{value}%"))
    else
      clients.joins(ports: :outputs)
             .where(arel_table[name]
             .matches("%#{value}%"))
    end
  end

  def match_and_search(result, input)
    return result unless input
    result.where.not(id: @clients.where.not(id: input.pluck(:id))).group(:id)
  end

  def match_or_search(result, input)
    return result if input.nil?
    result.nil? ? input : @clients.where(id: result.pluck(:id)).or(@clients.where(id: input.pluck(:id))).group(:id)
  end

end

app/views/clients/_search.html.erb
<div class="modal-content">
  <table class="responsive-table">
    <tr style="padding-bottom: 20px;">
      <td>
        <!-- Dropdown Trigger -->
        <a class='dropdown-button btn' href='#' data-activates='client'>Client</a>
        <!-- Dropdown Structure -->
        <ul id='client' class='dropdown-content'>
          <li><a href="#" onclick="addSearchOption('Client', 'Hostname');">Hostname</a></li>
          <li><a href="#" onclick="addSearchOption('Client', 'IP');">IP Adress</a></li>
          <li><a href="#" onclick="addSearchOption('Client', 'MAC');">MAC Adress</a></li>
          <li><a href="#" onclick="addSearchOption('Client', 'OS');">Operating System</a></li>
          <li><a href="#" onclick="addSearchOption('Client', 'CPE');">CPE</a></li>
        </ul>
      </td>
      <td>
        <!-- Dropdown Trigger -->
        <a class='dropdown-button btn' href='#' data-activates='port'>Port</a>
        <!-- Dropdown Structure -->
        <ul id='port' class='dropdown-content'>
          <li><a href="#" onclick="addSearchOption('Port', 'Number');">Number</a></li>
          <li><a href="#" onclick="addSearchOption('Port', 'Service');">Service</a></li>
          <li><a href="#" onclick="addSearchOption('Port', 'Description');">Description</a></li>
        </ul>
      </td>
      <td>
        <a class="btn" onclick="addSearchOption('Group', 'Name');">Group Name</a>
      </td>
      <td>
        <a class="btn" onclick="addSearchOption('Output', 'Value');">Script Output</a>
      </td>
      <td>
        <!-- Dropdown Trigger -->
        <a class='dropdown-button btn' href='#' data-activates='label'>Label</a>
        <!-- Dropdown Structure -->
        <ul id='label' class='dropdown-content'>
          <% Label.all.to_a.each do |lbl| %>
              <li><a href="#" onclick="this.blur(); addSearchOption('Label', '<%= lbl.name %>');"><%= lbl.name %></a></li>
          <% end %>
        </ul>
      </td>
      <td>
        <input name="search-name" id="search-name" placeholder="Search name ..." type="text" class="validate">
      </td>
      <td>
        <a class="btn green darken-2" id="submit-search" onclick="$('#global_search_form').submit();"><i class="material-icons">search</i></a>
      </td>
    </tr>
  </table>
  <div class="divider" style="margin-top: 10px; margin-bottom: 10px;"></div>
  <div class="section">
    <div class="row">
      <div class="col s4">
        <%= simple_form_for :search, url: global_search_path, remote: true, multipart: true, :html => { :onsubmit => 'pre_load();', :id => 'global_search_form' } do |f| %>
            <div id="end_of_form"></div>
        <% end %>
      </div>
      <div class="col s8">
        <div id="search_result"></div>
      </div>
    </div>
  </div>
</div>

<div class="modal-footer">
  <a href="#" class="btn modal-action blue darken-2" id="add_to_group_view">Add to Group-View</a>
  <a href="#" class="modal-action modal-close waves-effect waves-red btn-flat">Close</a>
</div>

<script language="JavaScript">
  // global form counter
  var forms = 1;

  // init dropdown button
  $('.dropdown-button').dropdown({
      constrainWidth: false, // Does not change width of dropdown to that of the activator
  });

  function addSearchOption(model, name) {
      var raw = `<div class="form_row">
          <div class="row">
          <input name="search[val${forms}[table]]" value="${model.toLowerCase()}" type="hidden">
          <input name="search[val${forms}[name]]" value="${name.toLowerCase()}" type="hidden">
            <div class="col s3" style="margin-top: 2em;">
              <a class="btn btn-small" onclick="reverse(this);">=</a>
              <input type="hidden" name="search[val${forms}[not]]" class="not" value="false">
            </div>
            <div class="input-field col s6">
              <input name="search[val${forms}[value]]" type="text" class="validate">
              <label class="active">${model} -> ${name}</label>
            </div>
            <div class="col s3" style="margin-top: 2em;">
              <a class="btn btn-small red darken-1 form_row_delete"><i class="material-icons">delete</i></a>
            </div>
          </div>
          <div class="row">
            <div class="col s11">
              <div class="switch center-align">
                <label>AND<input type="checkbox" name="search[val${forms}[or]]" value="true"><span class="lever"></span>OR</label>
              </div>
            </div>
          </div>
        </div>`;

      var raw_label = `<div class="form_row">
          <div class="row">
          <input name="search[val${forms}[table]]" value="${model.toLowerCase()}" type="hidden">
          <input name="search[val${forms}[name]]" value="name" type="hidden">
            <div class="col s3" style="margin-top: 2em;">
              <a class="btn btn-small" onclick="reverse(this);">=</a>
              <input type="hidden" name="search[val${forms}[not]]" class="not" value="false">
            </div>
            <div class="input-field col s6">
              <input name="search[val${forms}[value]]" value="${name}" type="text" class="validate" disabled>
              <input name="search[val${forms}[value]]" value="${name.toLowerCase()}" type="hidden">
              <label class="active">${model}</label>
            </div>
            <div class="col s3" style="margin-top: 2em;">
              <a class="btn btn-small red darken-1 form_row_delete"><i class="material-icons">delete</i></a>
            </div>
          </div>
          <div class="row">
            <div class="col s11">
              <div class="switch center-align">
                <label>AND<input type="checkbox" name="search[val${forms}[or]]" value="true"><span class="lever"></span>OR</label>
              </div>
            </div>
          </div>
        </div>`;

      if (model == "Label") {
          raw = raw_label;
      }

      // insert form row
      $(raw).insertBefore("#end_of_form").hide().fadeIn(300);

      // delete row button
      $('.form_row_delete').click(function () {
          $(this).parents('.form_row').fadeOut(300, function() {$(this).remove();});
      });

      // counter + 1
      forms = forms + 1;
  }

  // = --> != --> =
  function reverse(x) {
      if (x.innerHTML == "="){
          x.innerHTML = "!=";
          $(x).siblings(".not").val("true");
      } else {
          x.innerHTML = "=";
          $(x).siblings(".not").val("false");
      }
      x.blur();
  }

  function pre_load() {
    // disable search button
    $('#submit-search').addClass("disabled");

    // add spinner until query is ready
    $("#search_result").html('<div class="text-center" style="padding-top: 50px;"><div class="preloader-wrapper big active">\n' +
        '    <div class="spinner-layer spinner-blue-only">\n' +
        '      <div class="circle-clipper left">\n' +
        '        <div class="circle"></div>\n' +
        '      </div><div class="gap-patch">\n' +
        '        <div class="circle"></div>\n' +
        '      </div><div class="circle-clipper right">\n' +
        '        <div class="circle"></div>\n' +
        '      </div>\n' +
        '    </div>\n' +
        '  </div></div>');
        
    // add search name to form
    var sname = $("#search-name").val();
    search_name_input = `<input type="hidden" name="search_name" value="${sname}" type="text" class="validate">`;
    $(search_name_input).insertBefore("#end_of_form");
  }
</script>

app/views/clients/_search_result.html.erb
<% random_id = (0...15).map { ('a'..'z').to_a[rand(26)] }.join %>
<div class="row group-box scale-transition" id="box_<%= random_id %>">
   <div class="col s12" id="group_content_<%= random_id %>">
     <div class="card material-table">
       <div class="table-header">
         <span class="table-title"><i class="fa fa-search" aria-hidden="true"></i><span style="margin-left: 14px;"><%= "#{@search_name}" %></span></span>
         <div class="actions group-actions" id="<%= random_id %>">
           <a href="#" data-position="bottom" data-delay="50" data-tooltip="Export selected clients" class="btn-flat nopadding tooltipped grp_export"><i class="material-icons">file_download</i></a>
           <a href="#" data-position="bottom" data-delay="50" data-tooltip="Select all visible clients in group" class="btn-flat nopadding tooltipped grp_mark_all"><i class="material-icons">check_box</i></a>
           <a href="#" data-position="bottom" data-delay="50" data-tooltip="Unselect all visible clients in group" class="btn-flat nopadding tooltipped grp_unmark_all"><i class="material-icons">check_box_outline_blank</i></a>
           <a href="#" data-position="bottom" data-delay="50" data-tooltip="Delete selected clients" class="btn-flat nopadding tooltipped grp_delete_clients"><i class="material-icons red-text text-darken-4">delete</i></a>
           <a href="#" data-position="bottom" data-delay="50" data-tooltip="Move selected clients to another group" class="btn-flat nopadding tooltipped grp_move"><i class="material-icons blue-text text-darken-2">forward</i></a>
           <a href="#" data-position="bottom" data-delay="50" data-tooltip="Copy selected clients to another group" class="btn-flat nopadding tooltipped grp_copy"><i class="material-icons blue-text text-darken-2">content_copy</i></a>
           <a href="#" data-position="bottom" data-delay="50" data-tooltip="Add new group with selected clients" class="btn-flat nopadding tooltipped grp_new"><i class="material-icons green-text text-darken-2">group_add</i></a>
           <a href="#" data-position="bottom" data-delay="50" data-tooltip="Search in group" class="btn-flat nopadding tooltipped grp_search-toggle"><i class="material-icons yellow-text text-darken-4">search</i></a>
           <a href="#" data-position="bottom" data-delay="50" data-tooltip="Close group" class="btn-flat nopadding tooltipped grp_close"><i class="material-icons">close</i></a>
         </div>
       </div>
       <table id="datatable-<%= random_id %>" class="dt_init">
         <thead>
         <tr>
           <th>IP</th>
           <th>Hostname</th>
           <th>Operating System</th>
           <th>Ports</th>
         </tr>
         </thead>
         <tbody>
            <% @clients.order(:ip).to_a.each do |current_client| %>
              <tr>
                <td><%= link_to "#{current_client.ip}", client_path(current_client.id), :remote => true, :id => current_client.id %></td>
                <td><%= "#{current_client.hostname}" %></td>
                <td><%= "#{current_client.os}" %></td>
                <td><%= "#{current_client.ports.count}" %></td>
              </tr>
            <%  end %>
         </tbody>
       </table>
     </div>
   </div>
</div>

app/views/clients/_show.html.erb
<style>
  .chip-icon {
    cursor: pointer;
    float: right;
    font-size: 16px;
    line-height: 32px;
    padding-left: 8px;
  }
  .hostview_copy_ip {
    font-size: 18px;
    margin-left: 10px;
  }
  .hostview_link {
    font-size: 22px;
    margin-left: 10px;
    vertical-align: middle;
  }
</style>
<span class="card-title"><span id="hostview_ip"><%= "#{client.ip}" %></span><a href="#" id="hostview_copy_ip" onclick=""><i class="material-icons hostview_copy_ip">content_copy</i></a></span>
<table class="responsive-table">
  <thead>
    <tr>
      <th>Hostname</th>
      <th>MAC</th>
      <th>Labels</th>
      <th>Groups</th>
    </tr>
  <thead>
  <tbody>
    <tr>
      <td><%= "#{client.hostname}" %></td>
      <td><%= "#{client.mac}" %>
        <% if client.vendor.to_s.length > 0 %>
            <br />(<%= "#{client.vendor}" %>)
        <% end %>
      </td>
      <td>
        <% client.labels.to_a.each do |label|%>
            <div class="chip <%= label.priority%>"><%= label.name%></div>
        <% end %>
      </td>
      <td>
        <% client.groups.to_a.each do |group|%>
            <div class="chip"><%= group.name%></div>
        <% end %>
      </td>
    </tr>
  </tbody>
</table>
<div class="valign-wrapper" style="padding-bottom: 10px; padding-top: 20px">
  <i class="material-icons grey-text text-darken-2" style="margin-right: 5px;">settings</i><b>Operating System</b>
</div>
<p style="padding-bottom: 20px;"><%= "#{client.os}" %></p>
<table class="responsive-table">
  <thead>
    <tr>
      <th>Port</th>
      <th>Desc</th>
      <th>Content</th>
    </tr>
  <thead>
  <tbody>
    <% client.ports.all.order(:number).to_a.each do |port| %>
        <tr>
          <td>
            <span><%= "#{port.number}" %></span>
            <% if port.service.include? "http" %>
                  <a href="<% if port.service.include? "https" or port.number.to_s.include? "443" %>https<% else %>http<% end %>://<%= "#{port.client.ip}" %>:<%= "#{port.number}" %>" target="_blank"><i class="material-icons hostview_link ">link</i></a>
            <% end %>
          </td>
          <td><%= "#{port.service}" %></td>
          <td><%= "#{port.description}" %></td>
        </tr>
        <% if port.outputs.count > 0 %>
            <tr>
              <td colspan="3">
                <ul class="collapsible" data-collapsible="expandable">
                  <% port.outputs.to_a.each do |output| %>
                    <li>
                      <div class="collapsible-header"><i class="material-icons">short_text</i><%= "#{output.name}" %></div>
                      <div class="collapsible-body">
                        <% output.value.split(/\n/).each do |line| %>
                            <span><%= "#{line}"%></span>
                        <% end%>
                      </div>
                    </li>
                  <% end%>
                </ul>
              </td>
            </tr>
        <% end %>
    <% end %>
  </tbody>
</table>
<% if client.outputs.count > 0 %>
  <div class="valign-wrapper" style="padding-bottom: 20px; padding-top: 20px">
    <i class="material-icons grey-text text-darken-2" style="margin-right: 5px;">extension</i><b>Hostscripts</b>
    <span class="badge"><%= "#{client.outputs.count}"%></span>
  </div>
  <ul class="collapsible" data-collapsible="expandable">
    <% client.outputs.to_a.each do |output| %>
      <li>
        <div class="collapsible-header"><i class="material-icons">short_text</i><%= "#{output.name}" %></div>
        <div class="collapsible-body">
          <% output.value.split(/\n/).to_a.each do |cur_line| %>
              <span><%= "#{cur_line}"%></span>
          <% end%>
        </div>
      </li>
    <% end%>
  </ul>
  </div>
<% end %>

app/views/clients/search.js.erb
$("#wide-modal-content").html("<%= j(render('search')) %>");

app/views/clients/search_result.js.erb
// enable search button
$('#submit-search').removeClass("disabled");

// replace search result div with data table
$("#search_result").html("<%= j(render('search_result')) %>");


$('#add_to_group_view').click(function () {
    $('#search_result .group-box').prependTo("#single_group_view");
    $("#group-placeholder").addClass("hidden");
    $("#wide-modal").modal('close');
});

// Custom JS File for Datatables with Material Design
// Credits: https://codepen.io/anon/pen/BddNxJ

function init_datatables() {
    // Custom JS File for Datatables with Material Design
    // Credits: https://codepen.io/anon/pen/BddNxJ

    var factory = function($, DataTable) {
        "use strict";

        /* Set the defaults for DataTables initialisation */
        $.extend(true, DataTable.defaults, {
            dom: "<'hiddensearch'f'>" +
            "tr" +
            "<'table-footer'lip'>",
            renderer: 'material'
        });

        /* Default class modification */
        $.extend(DataTable.ext.classes, {
            sWrapper: "dataTables_wrapper",
            sFilterInput: "form-control input-sm",
            sLengthSelect: "form-control input-sm"
        });

        /* Bootstrap paging button renderer */
        DataTable.ext.renderer.pageButton.material = function(settings, host, idx, buttons, page, pages) {
            var api = new DataTable.Api(settings);
            var classes = settings.oClasses;
            var lang = settings.oLanguage.oPaginate;
            var btnDisplay, btnClass, counter = 0;

            var attach = function(container, buttons) {
                var i, ien, node, button;
                var clickHandler = function(e) {
                    e.preventDefault();
                    if (!$(e.currentTarget).hasClass('disabled')) {
                        api.page(e.data.action).draw(false);
                    }
                };

                for (i = 0, ien = buttons.length; i < ien; i++) {
                    button = buttons[i];

                    if ($.isArray(button)) {
                        attach(container, button);
                    } else {
                        btnDisplay = '';
                        btnClass = '';

                        switch (button) {

                            case 'first':
                                btnDisplay = lang.sFirst;
                                btnClass = button + (page > 0 ?
                                    '' : ' disabled');
                                break;

                            case 'previous':
                                btnDisplay = '<i class="material-icons">chevron_left</i>';
                                btnClass = button + (page > 0 ?
                                    '' : ' disabled');
                                break;

                            case 'next':
                                btnDisplay = '<i class="material-icons">chevron_right</i>';
                                btnClass = button + (page < pages - 1 ?
                                    '' : ' disabled');
                                break;

                            case 'last':
                                btnDisplay = lang.sLast;
                                btnClass = button + (page < pages - 1 ?
                                    '' : ' disabled');
                                break;

                        }

                        if (btnDisplay) {
                            node = $('<li>', {
                                'class': classes.sPageButton + ' ' + btnClass,
                                'id': idx === 0 && typeof button === 'string' ?
                                    settings.sTableId + '_' + button : null
                            })
                                .append($('<a>', {
                                        'href': '#',
                                        'aria-controls': settings.sTableId,
                                        'data-dt-idx': counter,
                                        'tabindex': settings.iTabIndex
                                    })
                                        .html(btnDisplay)
                                )
                                .appendTo(container);

                            settings.oApi._fnBindAction(
                                node, {
                                    action: button
                                }, clickHandler
                            );

                            counter++;
                        }
                    }
                }
            };

            // IE9 throws an 'unknown error' if document.activeElement is used
            // inside an iframe or frame.
            var activeEl;

            try {
                // Because this approach is destroying and recreating the paging
                // elements, focus is lost on the select button which is bad for
                // accessibility. So we want to restore focus once the draw has
                // completed
                activeEl = $(document.activeElement).data('dt-idx');
            } catch (e) {}

            attach(
                $(host).empty().html('<ul class="material-pagination"/>').children('ul'),
                buttons
            );

            if (activeEl) {
                $(host).find('[data-dt-idx=' + activeEl + ']').focus();
            }
        };
    }; // /factory

    // Define as an AMD module if possible
    if (typeof define === 'function' && define.amd) {
        define(['jquery', 'datatables'], factory);
    } else if (typeof exports === 'object') {
        // Node/CommonJS
        factory(require('jquery'), require('datatables'));
    } else if (jQuery) {
        // Otherwise simply initialise as normal, stopping multiple evaluation
        factory(jQuery, jQuery.fn.dataTable);
    }

    $('.dt_init').dataTable({
        "oLanguage": {
            "sStripClasses": "",
            "sSearch": "",
            "sSearchPlaceholder": "Enter Keywords Here",
            "sInfo": "_START_ -_END_ of _TOTAL_",
            "sLengthMenu": '<span>Rows per page:</span><select class="browser-default">' +
            '<option value="10">10</option>' +
            '<option value="20">20</option>' +
            '<option value="30">30</option>' +
            '<option value="40">40</option>' +
            '<option value="50">50</option>' +
            '<option value="-1">All</option>' +
            '</select></div>'
        },
        bAutoWidth: false
    });
    // remove dt-init marker
    $('.dt_init').removeClass('dt_init');
}

// Call init datatables
$('document').ready(init_datatables());

// tooltip reinit
$('document').ready(function() {
    $('.tooltipped').tooltip({delay: 50});
});

// Make table rows selectable except the a-Tags
$(".dataTable tbody").selectable({
    filter: 'tr',
    cancel: 'a'
});

app/views/clients/show.js.erb
$("#hostview").html("<%= j(render('show', :client=> client)) %>");
$("#hostview_copy_ip").click(function () {
    copyToClipboard('#hostview_ip');
    Materialize.toast('IP address copied to clipboard!', 2000, 'green');
});

function copyToClipboard(element) {
    var $temp = $("<input>");
    $("body").append($temp);
    $temp.val($(element).text()).select();
    document.execCommand("copy");
    $temp.remove();
}

$(document).ready(function(){
    $('.collapsible').collapsible();
});