config/routes.rb
Rails.application.routes.draw do
  #devise_for :users
  devise_for :users, controllers: { registrations: "registrations"}
  mount ActionCable.server => '/cable'
  root to: redirect(path: '/scans')

  get '/scans' => 'pages#scans'
  get 'notifications/new'

  # index ever used, ever?
  resources :groups, only: %i[create new]

  post 'groups/create_form' => 'groups#create_form'

  post 'groups/copy_form' => 'groups#copy_form'
  post 'groups/copy' => 'groups#copy'

  post 'groups/move_form' => 'groups#move_form'
  post 'groups/move' => 'groups#move'

  post 'groups/export_form' => 'groups#export_form'
  post 'groups/export' => 'groups#export'

  post 'groups/delete_form' => 'groups#delete_form'
  post 'groups/delete' => 'groups#delete'
  post 'groups/delete_clients_form' => 'groups#delete_clients_form'
  post 'groups/delete_clients' => 'groups#delete_clients'

  get 'pages/refresh' => 'pages#refresh', as: :group_refresh

  get '/pages/groups' => 'pages#groups'
  get '/pages/settings' => 'pages#settings', as: :global_settings
  post '/clients/global_search' => 'clients#global_search', as: :global_search

  get '/clients/search' => 'clients#search'
  post '/clients/search' => 'clients#search', as: :global_search_view
  #
  # order matters. keep this below other clients-routes, or it will always match.
  # alternatively, constraints need to be used (ie. regex for \d etc)
  get '/clients' => 'clients#index'
  get '/clients/:id' => 'clients#show'

  post 'setting/update_user_settings' => 'setting#update_user_settings', as: :update_user_settings
  post 'settings/update' => 'settings#update', as: :update_settings

  post 'scans/create' => 'scans#create'
  get 'scans/reload_status' => 'scans#reload_status'
  get 'scans/reload_finished' => 'scans#reload_finished'
  post 'scans/upload' => 'scans#upload'

  resources :clients

  # TODO: still used somewhere?
  post 'groups/scan_form' => 'groups#scan_form'
  post 'groups/scan' => 'groups#scan'


end

app/models/client.rb
class Client < ApplicationRecord
  has_many :ports, dependent: :destroy
  has_many :outputs, dependent: :destroy
  has_and_belongs_to_many :groups
  has_and_belongs_to_many :labels
end

app/views/pages/_group_tables.html.erb
<%  Group.all.order(mod: :desc, name: :asc).to_a.each do |current_group| %>
    <script type="application/javascript">
        if(!(($('#box_<%= "#{current_group.id}" %>').length) && !$('#box_<%= "#{current_group.id}" %>').hasClass("hidden"))) {
            var groupSkeleton =
                '<div class="row hidden group-box scale-transition" id="box_<%= "#{current_group.id}" %>">\n' +
                '   <div class="col s12" id="group_content_<%= "#{current_group.id}" %>"></div>\n' +
                '</div>'
            $(groupSkeleton).appendTo("#group_tables");
        }
    </script>
    <%= javascript_tag(render(:template => 'groups/group_content', :handlers => [:erb], :formats => [:js], locals:{group_ids: Array.new(1, current_group.id), message: "empty"})) %>
<%  end %>

<script>
    function init_datatables() {
        // Custom JS File for Datatables with Material Design
        // Credits: https://codepen.io/anon/pen/BddNxJ

        var factory = function($, DataTable) {
            "use strict";

            /* Set the defaults for DataTables initialisation */
            $.extend(true, DataTable.defaults, {
                dom: "<'hiddensearch'f'>" +
                "tr" +
                "<'table-footer'lip'>",
                renderer: 'material'
            });

            /* Default class modification */
            $.extend(DataTable.ext.classes, {
                sWrapper: "dataTables_wrapper",
                sFilterInput: "form-control input-sm",
                sLengthSelect: "form-control input-sm"
            });

            /* Bootstrap paging button renderer */
            DataTable.ext.renderer.pageButton.material = function(settings, host, idx, buttons, page, pages) {
                var api = new DataTable.Api(settings);
                var classes = settings.oClasses;
                var lang = settings.oLanguage.oPaginate;
                var btnDisplay, btnClass, counter = 0;

                var attach = function(container, buttons) {
                    var i, ien, node, button;
                    var clickHandler = function(e) {
                        e.preventDefault();
                        if (!$(e.currentTarget).hasClass('disabled')) {
                            api.page(e.data.action).draw(false);
                        }
                    };

                    for (i = 0, ien = buttons.length; i < ien; i++) {
                        button = buttons[i];

                        if ($.isArray(button)) {
                            attach(container, button);
                        } else {
                            btnDisplay = '';
                            btnClass = '';

                            switch (button) {

                                case 'first':
                                    btnDisplay = lang.sFirst;
                                    btnClass = button + (page > 0 ?
                                        '' : ' disabled');
                                    break;

                                case 'previous':
                                    btnDisplay = '<i class="material-icons">chevron_left</i>';
                                    btnClass = button + (page > 0 ?
                                        '' : ' disabled');
                                    break;

                                case 'next':
                                    btnDisplay = '<i class="material-icons">chevron_right</i>';
                                    btnClass = button + (page < pages - 1 ?
                                        '' : ' disabled');
                                    break;

                                case 'last':
                                    btnDisplay = lang.sLast;
                                    btnClass = button + (page < pages - 1 ?
                                        '' : ' disabled');
                                    break;

                            }

                            if (btnDisplay) {
                                node = $('<li>', {
                                    'class': classes.sPageButton + ' ' + btnClass,
                                    'id': idx === 0 && typeof button === 'string' ?
                                        settings.sTableId + '_' + button : null
                                })
                                    .append($('<a>', {
                                            'href': '#',
                                            'aria-controls': settings.sTableId,
                                            'data-dt-idx': counter,
                                            'tabindex': settings.iTabIndex
                                        })
                                            .html(btnDisplay)
                                    )
                                    .appendTo(container);

                                settings.oApi._fnBindAction(
                                    node, {
                                        action: button
                                    }, clickHandler
                                );

                                counter++;
                            }
                        }
                    }
                };

                // IE9 throws an 'unknown error' if document.activeElement is used
                // inside an iframe or frame.
                var activeEl;

                try {
                    // Because this approach is destroying and recreating the paging
                    // elements, focus is lost on the select button which is bad for
                    // accessibility. So we want to restore focus once the draw has
                    // completed
                    activeEl = $(document.activeElement).data('dt-idx');
                } catch (e) {}

                attach(
                    $(host).empty().html('<ul class="material-pagination"/>').children('ul'),
                    buttons
                );

                if (activeEl) {
                    $(host).find('[data-dt-idx=' + activeEl + ']').focus();
                }
            };
        }; // /factory

        // Define as an AMD module if possible
        if (typeof define === 'function' && define.amd) {
            define(['jquery', 'datatables'], factory);
        } else if (typeof exports === 'object') {
            // Node/CommonJS
            factory(require('jquery'), require('datatables'));
        } else if (jQuery) {
            // Otherwise simply initialise as normal, stopping multiple evaluation
            factory(jQuery, jQuery.fn.dataTable);
        }

        $('.dt_init').dataTable({
            "oLanguage": {
                "sStripClasses": "",
                "sSearch": "",
                "sSearchPlaceholder": "Enter Keywords Here",
                "sInfo": "_START_ -_END_ of _TOTAL_",
                "sLengthMenu": '<span>Rows per page:</span><select class="browser-default">' +
                '<option value="10">10</option>' +
                '<option value="20">20</option>' +
                '<option value="30">30</option>' +
                '<option value="40">40</option>' +
                '<option value="50">50</option>' +
                '<option value="-1">All</option>' +
                '</select></div>'
            },
            bAutoWidth: false
        });
        // remove dt-init marker
        $('.dt_init').removeClass('dt_init');
    }

    // Call init datatables
    $('document').ready(init_datatables());

    // tooltip reinit
    $('document').ready(function() {
        $('.tooltipped').tooltip({delay: 50});
    });

    //Make table rows selectable except the a-Tags
    $(".dataTable tbody").selectable({
        filter: 'tr',
        cancel: 'a'
    });
</script>

app/views/pages/_scan_finished.html.erb
<% Scan.where.not(enddate: nil).order(:id).each do |scan|%>
    <tr>
        <td class="custom-truncate" style="max-width: 5em;"><%= "#{scan.name}"%></td>
        <td class="custom-truncate tooltipped" style="max-width: 15em;" data-position="bottom" data-delay="50" data-tooltip="<%= "#{scan.command}"%>"><%= "#{scan.command}"%></td>
        <td><%= scan.startdate.blank? ? "": "#{scan.startdate.strftime('%Y-%m-%d %H:%M:%S')}"%></td>
        <td><%= scan.enddate.blank? ? "": "#{scan.enddate.strftime('%Y-%m-%d %H:%M:%S')}"%></td>
    </tr>
<% end%>

<script>
 $(document).ready(function(){
    $('.tooltipped').tooltip({delay: 50});
  });
</script>

app/views/pages/_scan_status.html.erb
<% Scan.where(enddate: nil).order(:id).each do |scan|%>
    <tr>
        <td class="custom-truncate" style="max-width: 5em;"><%= "#{scan.name}"%></td>
        <td class="custom-truncate"><%= "#{scan.command}"%></td>
        <td><%= scan.startdate.blank? ? "": "#{scan.startdate.strftime('%Y-%m-%d %H:%M:%S')}"%></td>
        <td>
        <div class="progress">
            <div class="determinate" style="width: <%= scan.status.blank? ? "0": "#{scan.status}"%>%"></div>
        </div>
        </td>
    </tr>
<% end%>

<script>
 $(document).ready(function(){
    $('.tooltipped').tooltip({delay: 50});
  });
</script>

app/views/pages/groups.html.erb
<style>
  .collection {
    border: none !important;
  }
  .collection.with-header .collection-header {
    background-color: transparent !important;
  }
  .collection .collection-item {
    background-color: transparent !important;
  }
  #group_list {
    padding-top: 10px;
    position: fixed;
    overflow-y: auto;
    max-height: calc(100vh - 140px);
    min-height: calc(100vh - 64px);
  }
  #single_group_view {
    padding-top: 10px;
    position: fixed;
    overflow-y: auto;
    max-height: calc(100vh - 140px);
    min-height: calc(100vh - 64px);
  }
  #single_host_view {
    padding-top: 10px;
    position: fixed;
    overflow-y: auto;
    max-height: calc(100vh - 140px);
    min-height: calc(100vh - 64px);
  }
  .collection .collection-item {
    border-bottom: none !important;
  }
  ::-webkit-scrollbar {
    display: none;
  }
  .collection a.collection-item:not(.active):hover {
    background-color: rgba(0,0,0,.05) !important;
  }
  .collection a.collection-item {
    color: #2E2F30 !important;
    font-weight: 500;
  }
  .secondary-content {
    color: #616161 !important;
  }
  .fa {
    font-size: 24px;
    color: #878284;
  }
  .group-icon-collection {
    float: left;
  }
  .hidden {
    display: none;
  }
  #single_host_view_card {
    min-height: calc(100vh - 8em);
  }
  .fixed-action-btn {
    right: 35px !important;
    bottom: 15px !important;
  }
  .btn-small {
    height: 28px;
    line-height: 28px;
    padding: 0 1.2rem;
  }
  .btn-small i {
    font-size: 1rem;
  }
  #wide-modal {
    width: 90% !important;
  }
  #medium-modal {
    width: 50% !important;
    z-index: 10000000 !important;
  }
  #generic-modal {
    z-index: 10000000 !important;  
  }
  .ui-selected{
    background: #edf4fd;
  }
  .ui-selecting{
    background: #edf4fd;
  }
  .table-header-groups {
    height: unset !important;
    display: grid !important;
  }
  .collapsible {
      box-shadow: none !important;
      border-right: none !important;
      border-left: none !important;
  }

</style>
<div class="row">
    <div class="col s2" id="group_list">
      <%= render partial: "group_list" %>
    </div>
    <div class="col s5 offset-s2" id="single_group_view">
      <div class="row" id="group-placeholder">
        <div class="col s12 m12">
          <div class="card">
            <div class="card-content">
              <span class="card-title">No group selected</span>
              <a class="btn-floating btn-large halfway-fab red group_add_float"><i class="material-icons">group_add</i></a>
              <p>Please select a group or create a new one.</p>
            </div>
          </div>
        </div>
      </div>
      <div id="group_tables">
        <%= render partial: "group_tables" %>
      </div>
    </div>
    <div class="col s5 offset-s7" id="single_host_view">
      <div class="row" id="group-placeholder">
        <div class="col s12 m12">
          <div class="card">
            <div class="card-content" id="single_host_view_card">
              <div id="hostview">
                <span class="card-title">Single Host View</span>
                <p>Please select a client to view the details.</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
</div>

<!-- Modal (generic) -->
<div id="generic-modal" class="modal modal-fixed-footer">
  <div id="modal-content">
  </div>
</div>

<!-- Modal (medium) -->
<div id="medium-modal" class="modal modal-fixed-footer">
  <div id="medium-modal-content">
  </div>
</div>

<!-- Modal (wide) -->
<div id="wide-modal" class="modal modal-fixed-footer">
  <div id="wide-modal-content">
  </div>
</div>

<div class="fixed-action-btn vertical">
  <a class="btn-floating btn-large blue darken-3">
    <i class="material-icons">menu</i>
  </a>
  <ul>
    <li><a class="btn-floating blue tooltipped group_refresh_float" data-position="left" data-delay="50" data-tooltip="Refresh group content"><i class="material-icons">refresh</i></a></li>
    <li><a class="btn-floating red tooltipped group_add_float" data-position="left" data-delay="50" data-tooltip="Add a group"><i class="material-icons">group_add</i></a></li>
    <li><a class="btn-floating green darken-2 tooltipped search_float" data-position="left" data-delay="50" data-tooltip="Global search"><i class="material-icons">search</i></a></li>
  </ul>
</div>

<script>
  // Display group on click (sidebar)
  $(document).on("click", '.group-collection-item', function() {
      $("#group-placeholder").addClass("hidden");
      var id = this.id.split("_")[1];
      $("#box_" + id).prependTo("#single_group_view");
      $("#box_" + id).fadeIn(400);
      $("#box_" + id).removeClass("hidden");
      $(this).blur();
  });

  // Datatable Search toogle with more than one datatables
  $(document).on("click", '.grp_search-toggle', function() {
      if ($(this).parents(".table-header").siblings(".dataTables_wrapper").find(".hiddensearch").css('display') == 'none')
          $(this).parents(".table-header").siblings(".dataTables_wrapper").find(".hiddensearch").slideDown();
      else
          $(this).parents(".table-header").siblings(".dataTables_wrapper").find(".hiddensearch").slideUp();

      $(this).blur();
  });

  // Close Group Box
  $(document).on("click", '.grp_close', function() {
      var id = $(this).parents(".group-actions").attr('id');
      $(this).blur();
      $("#box_" + id).fadeOut(400, function() {
          $("#box_" + id).addClass("hidden");
          $("#box_" + id).appendTo("#group_tables");
          $("#box_" + id).promise().done(function(){
              // Show placeholder if all groups are hidden
              if ($(".group-box").filter(".hidden").length == $(".group-box").length)
                  $("#group-placeholder").removeClass("hidden");
          });
      });
  });

  // new group add - group header
  $(document).on("click", '.grp_new', function() {
      var search = false;
      var clients = new Array();
      var id = $(this).parent().attr("id");
      $("#datatable-" +  id).find(".ui-selectable tr a").each(function() {
          if($(this).parents(".ui-selectee").hasClass("ui-selected")) {
              clients.push($(this).attr("id"));
          }
      });

      // check if source group is search result
      if (id.length == 15) { search = true; }

      if(clients.length == 0){
          $.ajax({
            url: "<%= new_group_path %>",
              dataType : "script",
              cache: true
          });
      } else {
          $("#medium-modal").modal('open');
          $.ajax({
              url: "<%= groups_create_form_path %>",
              dataType : "script",
              cache: true,
              method: "post",
              data: {
                  clients: clients,
                  source_group: id,
                  search: search
              }
          });
      }
      $(this).blur();
  });

  // copy selected clients - group header
  $(document).on("click", '.grp_copy', function() {
      var search = false;
      var clients = new Array();
      var id = $(this).parent().attr("id");
      $("#datatable-" +  id).find(".ui-selectable tr a").each(function() {
          if($(this).parents(".ui-selectee").hasClass("ui-selected")) {
              clients.push($(this).attr("id"));
          }
      });

      // check if source group is search result
      if (id.length == 15) { search = true; }

      $.ajax({
          url: "<%= groups_copy_form_path %>",
          dataType : "script",
          cache: true,
          method: "post",
          data: {
              clients: clients,
              source_group: id,
              search: search
          }
      });

      $(this).blur();
  });

  // move selected clients - group header
  $(document).on("click", '.grp_move', function() {
      var search = false;
      var clients = new Array();
      var id = $(this).parent().attr("id");
      $("#datatable-" +  id).find(".ui-selectable tr a").each(function() {
          if($(this).parents(".ui-selectee").hasClass("ui-selected")) {
              clients.push($(this).attr("id"));
          }
      });

      // check if source group is search result
      if (id.length == 15) { search = true; }

      $.ajax({
          url: "<%= groups_move_form_path %>",
          dataType : "script",
          cache: true,
          method: "post",
          data: {
              clients: clients,
              source_group: id,
              search: search
          }
      });

      $(this).blur();
  });

  // delete selected clients - group header
  $(document).on("click", '.grp_delete_clients', function() {
      var search = false;
      var clients = new Array();
      var id = $(this).parent().attr("id");
      $("#datatable-" +  id).find(".ui-selectable tr a").each(function() {
          if($(this).parents(".ui-selectee").hasClass("ui-selected")) {
              clients.push($(this).attr("id"));
          }
      });

      // check if source group is search result
      if (id.length == 15) { search = true; }

      $.ajax({
          url: "<%= groups_delete_clients_form_path %>",
          dataType : "script",
          cache: true,
          method: "post",
          data: {
              clients: clients,
              source_group: id,
              search: search
          }
      });

      $(this).blur();
  });

  // delete group with all clients containing - group header
  $(document).on("click", '.grp_delete', function() {
      var clients = new Array();
      var id = $(this).parent().attr("id");
      $("#datatable-" +  id).find(".ui-selectable tr a").each(function() {
          if($(this).parents(".ui-selectee")) {
              clients.push($(this).attr("id"));
          }
      });

      $.ajax({
        url: "<%= groups_delete_form_path %>",
          dataType : "script",
          cache: true,
          method: "post",
          data: {
              clients: clients,
              source_group: id
          }
      });

      $(this).blur();
  });

  // export selected clients - group header
  $(document).on("click", '.grp_export', function() {
      var clients = new Array();
      var id = $(this).parent().attr("id");
      $("#datatable-" +  id).find(".ui-selectable tr a").each(function() {
          if($(this).parents(".ui-selectee").hasClass("ui-selected")) {
              clients.push($(this).attr("id"));
          }
      });

      $.ajax({
          url: "<%= groups_export_form_path %>",
          dataType : "script",
          cache: true,
          method: "post",
          data: {
              clients: clients
          }
      });

      $(this).blur();
  });

  // mark all clients in group - group header
  $(document).on("click", '.grp_mark_all', function() {
      var id = $(this).parent().attr("id");

      $("#datatable-" +  id).find(".ui-selectable tr a").each(function() {
          $(this).parents(".ui-selectee").addClass("ui-selected");

      });
      //$(this).blur();
  });

  // unmark all clients in group - group header
  $(document).on("click", '.grp_unmark_all', function() {
      var id = $(this).parent().attr("id");

      $("#datatable-" +  id).find(".ui-selectable tr a").each(function() {
          $(this).parents(".ui-selectee").removeClass("ui-selected");

      });
      $(this).blur();
  });

  // search -> button float & header
  $(".search_float, .search_header").click(function () {
      $("#wide-modal").modal('open');
      $.ajax({
        url: "<%= global_search_view_path %>",
          dataType : "script",
          cache: true
      });
  });

  // new group add -> button float
  $(".group_add_float").click(function () {
      $("#generic-modal").modal('open');

      $.ajax({
          url: "<%= new_group_path %>",
          dataType : "script",
          cache: true
      });
  });

  // new group add -> button float
  $(".group_refresh_float").click(function () {
      $.ajax({
        url: "<%= group_refresh_path %>",
          dataType : "script",
          cache: true
      });
  });

</script>

app/views/pages/scans.html.erb
<div class="row" style="padding-top: 2em;">
  <div class="col s6">
    <div class="container">
      <div class="row">
        <div class="col s12">
          <ul class="tabs tabs-fixed-width">
            <li class="tab col s3"><a href="#prescan">Preconfigured Scan</a></li>
            <li class="tab col s3"><a href="#upload">Upload nmap-XML</a></li>
            <li class="tab col s3"><a href="#manscan">Manual Scan</a></li>
          </ul>
        </div>
        <div id="prescan" class="col s12">
          <div class="white">
            <div class="container">
              <div class="row" style="padding: 2em;">
                <%= simple_form_for :scan, url: scans_create_path, remote: true, authenticity_token: true,  html: {multipart: true} do |f| %>
                  <div class="input-field col s8">
                    <select name="command" onchange="if (this.selectedIndex) setSavedScanLabel(this.options[this.selectedIndex].value);">
                      <option value="" disabled selected>Choose an option</option>
                      <% SavedScan.all.to_a.each do | saved_scan | %>
                        <option value="<%= saved_scan.parameter %>"><%= saved_scan.name %></option>
                      <% end %>
                    </select>
                    <label id="savedScanLabel">Scan Parameters*</label>
                  </div>
                  <div class="input-field col s4">
                    <input id="scan_target" placeholder="e.g. 10.4.10.0/24" name="target" type="text" class="validate">
                    <label for="scan_target">Target*</label>
                  </div>
                  <div class="input-field col s8">
                    <input id="scan_name" placeholder="e.g. internal network" name="name" type="text" class="validate">
                    <label for="scan_name">Name*</label>
                  </div>
                  <div class="input-field col s3">
                    <button class="btn" type="submit" name="action"><i class="fa fa-coffee"></i></button>
                  </div>
                  <div class="input-field col s1">
                    <i class="material-icons tooltipped" data-position="bottom" data-delay="50" data-tooltip="These scans are preconfigured and can be modified in the settings page.">info_outline</i>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
        <div id="upload" class="col s12">
          <div class="white">
            <div class="container">
              <div class="row" style="padding: 2em;">
                <%= simple_form_for :scan, url: scans_upload_path, remote: true, authenticity_token: true, html: {multipart: true} do |f| %>
                  <div class="file-field input-field col s12">
                    <div class="btn btn-small">
                      <i class="fa fa-code"></i>
                      <input id="xml_file_" name="xml_file[]" type="file" accept=".xml" multiple>
                    </div>
                    <div class="file-path-wrapper">
                      <input class="file-path validate" type="text" placeholder="Upload one or several files">
                    </div>
                  </div>
                  <div class="input-field col s8">
                    <input id="scan_name" name="name" placeholder="e.g. internal network" type="text" class="validate">
                    <label for="scan_name">Scan Name</label>
                  </div>
                  <div class="input-field col s3">
                    <button class="btn" type="submit" name="action"><i class="fa fa-upload"></i></button>
                  </div>
                  <div class="input-field col s1">
                    <i class="material-icons tooltipped" data-position="bottom" data-delay="50" data-tooltip="Here you can upload nmap results generated by the '-oX' parameter">info_outline</i>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
        <div id="manscan" class="col s12">
          <div class="white">
            <div class="container">
              <div class="row" style="padding: 2em;">
                <%= simple_form_for :scan, url: scans_create_path, remote: true, authenticity_token: true,  html: {multipart: true} do |f| %>
                  <div class="input-field col s8">
                    <input id="scan_paramater" placeholder="e.g. -sV -p 8000,252,447 -n" name="command" type="text" class="validate">
                    <label for="scan_paramater">Nmap Parameter*</label>
                  </div>
                  <div class="input-field col s4">
                    <input id="scan_target" placeholder="e.g. 10.4.10.0/24" name="target" type="text" class="validate">
                    <label for="scan_target">Target*</label>
                  </div>
                  <div class="input-field col s8">
                    <input id="scan_name" placeholder="e.g. internal network" name="name" type="text" class="validate">
                    <label for="scan_name">Name*</label>
                  </div>
                  <div class="input-field col s3">
                    <button class="btn" type="submit" name="action"><i class="fa fa-coffee"></i></button>
                  </div>
                  <div class="input-field col s1">
                    <i class="material-icons tooltipped" data-position="bottom" data-delay="50" data-tooltip="Here you can start custom nmap scans. Some parameters (like '-oX') will be ignored/stripped from your input.">info_outline</i>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col s6">
    <div class="container">
      <div class="row">
        <div class="col s12">
          <ul class="tabs tabs-fixed-width">
            <li class="tab col s3"><a href="#running">Running</a></li>
            <li class="tab col s3"><a href="#finished">Finished</a></li>
          </ul>
        </div>
        <div id="running" class="col s12">
          <div class="white">
            <div class="container">
              <div class="row " style="padding: 2em;">
                <table class="responsive-table">
                  <thead>
                  <tr>
                    <th>Name</th>
                    <th>Command</th>
                    <th>Start Date</th>
                    <th>Status</th>
                  </tr>
                  </thead>
                  <tbody class="reload_status">
                    <%= render partial: "scan_status" %>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
        <div id="finished" class="col s12">
          <div class="white">
            <div class="container">
              <div class="row" style="padding: 2em;">
                <table class="responsive-table">
                  <thead>
                  <tr>
                    <th>Name</th>
                    <th>Command</th>
                    <th>Start date</th>
                    <th>End Date</th>
                  </tr>
                  </thead>
                  <tbody class="reload_finished">
                    <%= render partial: "scan_finished" %>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  $(document).ready(
    function() {
    setInterval(function() {
      $('.tooltipped').tooltip('remove');
      $('.reload_status').load('/scans/reload_status');
      $('.reload_finished').load('/scans/reload_finished');
    }, 10000);
  });
  function setSavedScanLabel(saved_scan){
    $("#savedScanLabel")[0].innerHTML = "Scan Parameter* ( " + saved_scan + " )";
  }
</script>